### ISSUE TITLE
Adafruit_TinyUSB renamed USBDevice to TinyUSBDevice

### ISSUE THREAD

**Issue by guruthree** [cyborg5/TinyUSB_Mouse_and_Keyboard#3]
As per https://github.com/adafruit/Adafruit_TinyUSB_Arduino/commit/4224cac621896db7bcde18da356b65b37c896b34, Adafruit renamed USBDevice to TinyUSBDevice. https://github.com/cyborg5/TinyUSB_Mouse_and_Keyboard/blob/master/TinyUSB_Mouse_and_Keyboard.cpp should be updated to  match.

**Comment by cyborg5** [comment]
Thank you for the heads up. The library still compiles because they put in a backward compatibility definition in "Adafruit_USBD_Device.h" which says 
```

#ifdef USE_TINYUSB
#define USBDevice  TinyUSBDevice
#endif
```
but I should probably update the code anyway.
