### ISSUE TITLE
Using Serial

### ISSUE THREAD

**Issue by crashmeplease** [cyborg5/TinyUSB_Mouse_and_Keyboard#6]
When using serial and keyboard (presume this is the same for mouse also), I find that I have to call Keyboard.begin() before Serial.begin(9600etc) otherwise the board will crash.

I am using an Adafruit QT Py RP2040 (4900)

i.e this works ok;

```
  Keyboard.begin();
  delay(5000);
  Keyboard.println("hello");
  
  Serial.begin(9600);
  delay(5000);
  Serial.println("Starting up..."); 
```

Where as this way fails;

```
  Serial.begin(9600);
  delay(5000);
  Serial.println("Starting up..."); 

  Keyboard.begin();
  delay(5000);
  Keyboard.println("hello");
```

Hope this helps anyone stuck with this issue.

**Comment by cyborg5** [comment]
In the example code, we use Keyboard.began() before the Serial.began(9600) and the "readme.md" states "Known issues: Intermittent problems using Serial.print() or Serial.println() but it is not always reproducible. We're working on it."

I still don't know why the order is critical or why it sometimes works and sometimes doesn't but if you use the order of initializing the keyboard or mouse before the serial it seems to be pretty stable.

**Comment by IrregularCelery** [comment]
I had some issues with the Serial communications like let's say we have this code:
```cpp
Serial.println("First");
delay(1000);
Serial.println("Second");
delay(1000);
```

You expect the output to be like:
`First -> delay -> Second -> delay`
but the actual result would be:
`Second + First (at the same time) -> delay`

After testing some solutions and watching their behaviours it seems like if you do a 
```
Serial.flush();
```
after each `Serial.print()` it should work as intended:
`First -> delay -> Second -> delay`

Hope it helps!
